#ifdef BACKWARD
#include "backward/backward.hpp"
namespace backward {
backward::SignalHandling sh;
} // namespace backward
#endif

#include "argh.h"
#include "game.h"
#include "headless_screenshots.h"
#include "preload.h"
#include "settings.h"
#include <afterhours/src/graphics.h>
#include <afterhours/src/plugins/files.h>
#include "systems/ExampleScreenRegistry.h"
// Screen registrations (auto-generated by makefile from src/systems/screens/*.h)
#include "screen_includes.gen"
#include "testing/e2e_integration.h"
#include "testing/test_macros.h"
#include "testing/tests/all_tests.h"
#include <cstdio>
#include <iostream>
#include <sstream>

#ifdef AFTER_HOURS_ENABLE_MCP
#include "engine/input_injector.h"
#include <afterhours/src/plugins/mcp_server.h>
#ifndef _WIN32
#include <unistd.h>
#endif
#endif

using namespace afterhours;

#ifdef AFTER_HOURS_ENABLE_MCP
bool g_mcp_mode = false;
int g_saved_stdout_fd = -1; // Used by MCP to write JSON to original stdout
#endif

bool g_headless_mode = false;
std::string g_headless_output_dir = "output/";

int main(int argc, char *argv[]) {
  argh::parser cmdl(argc, argv, argh::parser::PREFER_PARAM_FOR_UNREG_OPTION);

#ifdef AFTER_HOURS_ENABLE_MCP
  // Check for MCP mode EARLY and redirect stdout to stderr to keep stdout clean
  // for JSON protocol
  if (cmdl["--mcp"]) {
    g_mcp_mode = true;
#ifndef _WIN32
    // Save original stdout and redirect it to stderr
    // MCP will use write() directly to the saved fd
    g_saved_stdout_fd = dup(STDOUT_FILENO);
    dup2(STDERR_FILENO, STDOUT_FILENO);
#endif
  }
#endif

  if (cmdl["--help"]) {
    std::cout << "UI Tester \n\n";
    std::cout << "Usage: ui_tester [OPTIONS]\n\n";
    std::cout << "Options:\n";
    std::cout << "  --help                        Show this help message\n";
    std::cout
        << "  -w, --width <pixels>          Screen width (default: 1280)\n";
    std::cout
        << "  -h, --height <pixels>         Screen height (default: 720)\n";
    std::cout << "  --list-tests                 List all available tests\n";
    std::cout << "  --run-test <name>            Run a specific test\n";
    std::cout << "  --run-all-tests              Run all tests headlessly (for CI)\n";
    std::cout
        << "  --slow                       Run test in slow mode (visible)\n";
    std::cout << "  --hold-on-end                Keep window open after test "
                 "finishes\n";
    std::cout << "  --list-screens               List all available example "
                 "screens\n";
    std::cout << "  --screen=<name>              Show example screen (e.g., "
                 "--screen=simple_button)\n";
    std::cout << "                               Navigation: , (prev) . (next) "
                 "PageUp/PageDown\n";
#ifdef AFTER_HOURS_ENABLE_MCP
    std::cout << "  --mcp                        Enable MCP server mode\n";
#endif
    std::cout << "  --headless-screenshots [dir] Render all screens to PNG without display (default: output/)\n";
    std::cout << "  --image-backend              Alias for --headless-screenshots\n";
    std::cout << "  --image-output <dir>         Output directory override (default: output/)\n";
    std::cout << "  --resolution <res,...>        Resolutions for headless screenshots (default: 720p)\n";
    std::cout << "                               Examples: --resolution=480p,720p,1080p\n";
    std::cout << "                               Named: 480p (854x480), 720p (1280x720), 1080p (1920x1080)\n";
    std::cout << "                               Custom: --resolution=1600x900\n";
    std::cout << "\nE2E Testing:\n";
    std::cout << "  --e2e                        Enable E2E test mode\n";
    std::cout << "  --test-script <path>         Run single E2E script\n";
    std::cout << "  --test-script-dir <path>     Run all .e2e scripts in directory\n";
    std::cout << "  --timeout <seconds>          Set E2E timeout (default: 30)\n";
    std::cout << "  --slow                       Run tests slowly for visibility (0.5s delay)\n";
    std::cout << "  --slow-delay <seconds>       Set slow mode delay (implies --slow)\n";
    std::cout << "  --update-baselines           Update baseline screenshots instead of comparing\n";
    std::cout << "  --headless                   Run E2E tests without a window (for CI)\n";
    std::cout << "  --time-scale <float>         Time multiplier for headless mode (default: 1.0, e.g., 10.0 = 10x faster)\n";
    std::cout << "  --capture-interval <int>     Auto-capture screenshot every N frames (0 = disabled)\n";
    return 0;
  }

  if (cmdl["--list-tests"]) {
    TestRegistry &registry = TestRegistry::get();
    std::cout << "Available tests:\n";
    for (const auto &[name, func] : registry.tests) {
      std::cout << "  - " << name << "\n";
    }
    return 0;
  }

  if (cmdl["--run-all-tests"]) {
    int failures = run_all_tests_headless();
    return failures == 0 ? 0 : 1;
  }

  if (cmdl["--list-screens"]) {
    ExampleScreenRegistry::get().list_screens();
    return 0;
  }

  // Headless screenshots mode
  // Check both as flag (--headless-screenshots alone) and as parameter (--headless-screenshots <dir>)
  std::string headless_output_dir;
  bool has_headless_flag = cmdl["--headless-screenshots"];
  bool has_headless_param = static_cast<bool>(cmdl({"--headless-screenshots"}) >> headless_output_dir);
  // Also check --image-backend as an alias
  bool has_image_backend = cmdl["--image-backend"];

  if (has_headless_flag || has_headless_param || has_image_backend) {
    g_headless_mode = true;

    // Determine output directory
    std::string output_dir = "output/";
    if (has_headless_param && !headless_output_dir.empty()) {
      output_dir = headless_output_dir;
    }
    std::string image_output_override;
    if (cmdl({"--image-output"}) >> image_output_override) {
      output_dir = image_output_override;
    }
    g_headless_output_dir = output_dir;

    // Parse --resolution flag (comma-separated list of named or WxH values)
    std::string resolution_str;
    if (cmdl({"--resolution"}) >> resolution_str) {
      // Parse comma-separated resolution specs
      std::istringstream ss(resolution_str);
      std::string token;
      while (std::getline(ss, token, ',')) {
        // Trim whitespace
        while (!token.empty() && token.front() == ' ') token.erase(token.begin());
        while (!token.empty() && token.back() == ' ') token.pop_back();
        if (token.empty()) continue;

        if (token == "480p") {
          g_headless_resolutions.push_back({854, 480, "480p"});
        } else if (token == "720p") {
          g_headless_resolutions.push_back({1280, 720, "720p"});
        } else if (token == "1080p") {
          g_headless_resolutions.push_back({1920, 1080, "1080p"});
        } else {
          // Try WxH format
          auto x_pos = token.find('x');
          if (x_pos != std::string::npos) {
            int w = std::stoi(token.substr(0, x_pos));
            int h = std::stoi(token.substr(x_pos + 1));
            std::string label = std::to_string(h) + "p";
            g_headless_resolutions.push_back({w, h, label});
          } else {
            std::cout << "Warning: ignoring unknown resolution: " << token << "\n";
          }
        }
      }
    }
    // Default: 720p if no --resolution specified
    // (g_headless_resolutions empty → run_headless_screenshots defaults to 720p)

    std::cout << "Headless mode enabled, output dir: " << g_headless_output_dir << "\n";
    if (!g_headless_resolutions.empty()) {
      std::cout << "Resolutions:";
      for (const auto &r : g_headless_resolutions) {
        std::cout << " " << r.label << "(" << r.width << "x" << r.height << ")";
      }
      std::cout << "\n";
    }
    run_headless_screenshots();
    return 0;
  }

  // E2E Testing Mode
  if (e2e::should_run_e2e(argc, argv)) {
    auto e2e_args = e2e::parse_e2e_args(argc, argv);

    if (e2e_args.script_path.empty() && e2e_args.script_dir.empty()) {
      std::cout << "E2E mode requires --test-script or --test-script-dir\n";
      return 1;
    }

    int screenWidth, screenHeight;
    cmdl({"-w", "--width"}, 1280) >> screenWidth;
    cmdl({"-h", "--height"}, 720) >> screenHeight;

    Settings::get().load_save_file(screenWidth, screenHeight);

    if (e2e_args.headless) {
      // Headless mode: use graphics abstraction instead of Preload
      afterhours::graphics::Config cfg;
      cfg.display = afterhours::graphics::DisplayMode::Headless;
      cfg.width = screenWidth;
      cfg.height = screenHeight;
      cfg.title = "UI Tester - E2E Headless";
      cfg.target_fps = 60;
      cfg.time_scale = e2e_args.time_scale;

      if (!afterhours::graphics::init(cfg)) {
        std::cout << "Failed to initialize headless graphics backend\n";
        return 1;
      }

      // Enable auto-capture if requested
      if (e2e_args.capture_interval > 0) {
        std::string output_dir = "output/";
        afterhours::graphics::capture_every_n_frames(e2e_args.capture_interval, output_dir);
      }

      // Initialize files plugin (normally done by Preload::init)
      afterhours::files::init("Prime Pressure", "resources");

      // Create singletons (normally done by Preload::make_singleton)
      Preload::get().make_singleton();
    } else {
      // Normal windowed mode
      Preload::get()
          .init("UI Tester - E2E Mode")
          .make_singleton();
    }
    Settings::get().refresh_settings();

    // Set up test mode
    afterhours::testing::test_input::detail::test_mode = true;

    // Create and configure runner
    afterhours::testing::E2ERunner runner;
    runner.set_timeout(e2e_args.timeout_seconds);
    if (e2e_args.slow_mode) {
      runner.set_slow_mode(true, e2e_args.slow_delay);
    }
    runner.set_reset_callback(reset_e2e_state);

    // Load scripts
    if (!e2e_args.script_path.empty()) {
      runner.load_script(e2e_args.script_path);
    } else if (!e2e_args.script_dir.empty()) {
      runner.load_scripts_from_directory(e2e_args.script_dir);
    }

    if (!runner.has_commands()) {
      std::cout << "No E2E commands found to execute\n";
      return 1;
    }

    std::cout << "Running E2E tests...\n";

    int result = run_e2e_tests(e2e_args, runner);

    // Cleanup headless graphics if used
    if (e2e_args.headless) {
      afterhours::graphics::shutdown();
    }

    return result;
  }

  // Try --screen=<name> format first (preferred)
  std::string screen_name;
  cmdl({"--screen"}) >> screen_name;

  // Fallback: support legacy --<name> format for backwards compatibility
  if (screen_name.empty()) {
    for (const auto &arg : cmdl.flags()) {
      // argh returns flags without the "--" prefix
      if (arg != "help" && arg != "list-tests" && arg != "list-screens" &&
          arg != "slow" && arg != "hold-on-end" && arg != "run-test" &&
          arg != "mcp" && arg != "screen") {
        // Remove "--" prefix if present (in case it's there)
        if (arg.size() >= 2 && arg[0] == '-' && arg[1] == '-') {
          screen_name = arg.substr(2);
        } else {
          screen_name = arg;
        }
        break;
      }
    }
  }

  if (!screen_name.empty()) {
    if (ExampleScreenRegistry::get().has_screen(screen_name)) {
      int screenWidth, screenHeight;
      cmdl({"-w", "--width"}, 1280) >> screenWidth;
      cmdl({"-h", "--height"}, 720) >> screenHeight;

      Settings::get().load_save_file(screenWidth, screenHeight);

      Preload::get() //
          .init("UI Tester")
          .make_singleton();
      Settings::get().refresh_settings();

      bool hold_on_end = cmdl["--hold-on-end"];

      run_screen_demo(screen_name, hold_on_end);

      Settings::get().write_save_file();

      return 0;
    } else {
      std::cout << "Unknown screen: " << screen_name << "\n";
      std::cout << "Use --list-screens to see available screens\n";
      return 1;
    }
  }

  std::string test_name;
  if (cmdl({"--run-test"}) >> test_name) {
    bool slow_mode = cmdl["--slow"];
    bool hold_on_end = cmdl["--hold-on-end"];

    int screenWidth, screenHeight;
    cmdl({"-w", "--width"}, 1280) >> screenWidth;
    cmdl({"-h", "--height"}, 720) >> screenHeight;

    Settings::get().load_save_file(screenWidth, screenHeight);

    Preload::get() //
        .init("UI Tester")
        .make_singleton();
    Settings::get().refresh_settings();

    run_test(test_name, slow_mode, hold_on_end);

    Settings::get().write_save_file();

    return 0;
  }

  std::vector<std::string> screen_names =
      ExampleScreenRegistry::get().get_screen_names();
  if (screen_names.empty()) {
    std::cout << "No screens available. Run with --list-screens to see "
                 "available screens.\n";
    return 1;
  }

  int screenWidth, screenHeight;
  cmdl({"-w", "--width"}, 1280) >> screenWidth;
  cmdl({"-h", "--height"}, 720) >> screenHeight;

  Settings::get().load_save_file(screenWidth, screenHeight);

  Preload::get() //
      .init("UI Tester")
      .make_singleton();
  Settings::get().refresh_settings();

  bool hold_on_end = cmdl["--hold-on-end"];
#ifdef SINGLE_SCREEN_NAME
  run_screen_demo(SINGLE_SCREEN_NAME, hold_on_end);
#else
  run_screen_demo(screen_names[0], hold_on_end);
#endif

  Settings::get().write_save_file();

  return 0;
}
